### ISSUE TITLE
pytim not closing files

### ISSUE THREAD

**Issue by michaelservis** [Marcello-Sega/pytim#114]
When I run pytim.ITIM sufficient times in a python script, I get a "too many open files" error. I think that some files are not being closed when ITIM runs. They are only closed when the script calling ITIM terminates.

**Comment by Marcello-Sega** [comment]
Hi, 
thanks for reporting this. Could you post a minimal script that reproduces this problem? 
M

**Comment by Marcello-Sega** [comment]
possibly fixed by #205
