### ISSUE TITLE
MDAnalysis version

### ISSUE THREAD

**Issue by balazsfabian** [Marcello-Sega/pytim#117]
Tried to run pytim with MDA version 0.15.0, which is mentioned in the requirements.txt and setup.py.
However, on creating an ITIM object, the code tells me that I should use 0.16.x or newer. Can't we just require MDA 0.16.x or newer in the setup.py?

**Comment by Marcello-Sega** [comment]
Hi, thanks. I fixed the requirements in  4ded0da  
I guess we can close this?

**Comment by balazsfabian** [comment]
Not yet...
I wanted to do some cleanup (which I'm going to do), but when I applied the modifications and run a doctest, it failed some. After, I re-run the doctest for your last commit 4ded0da and I encountered the same problems? How come that Travis did not catch this?

The relevant output:

Document: ITIM
--------------
**********************************************************************
File "ITIM.rst", line 56, in default
Failed example:
    selection = np.logical_and(interface.atoms.layers == 2 , selection)
Exception raised:
    Traceback (most recent call last):
      File "/Users/bfabian/.pyenv/versions/2.7.14/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[2]>", line 1, in <module>
        selection = np.logical_and(interface.atoms.layers == 2 , selection)
    NameError: name 'np' is not defined
**********************************************************************
File "ITIM.rst", line 57, in default
Failed example:
    interface.atoms[ selection ] # upper side, second layer
Expected:
    <AtomGroup with 690 atoms>
Got:
    <AtomGroup with 2823 atoms>
**********************************************************************
1 items had failures:
   2 of  40 in default
40 tests in 1 items.
38 passed and 2 failed.
***Test Failed*** 2 failures.

**Comment by Marcello-Sega** [comment]
It was a missing import in one docstring, fixed now by  56c7490  

The reason why Travis didn't spot it is that I've switched to py.test, see `.travis.yml` :
    
    py.test --cov=pytim pytim/*py --doctest-modules 

Now it passes again also `make doctest`

**Comment by Marcello-Sega** [comment]
Actually, I did not observe the second failure. Let me know if it still shows up.

**Comment by balazsfabian** [comment]
56c7490 solved both issues on my machine

**Comment by Marcello-Sega** [comment]
Close the issue then :)

**Comment by balazsfabian** [comment]
Issue resolved by d7e76d0

**Comment by balazsfabian** [comment]
Issue resolved by d7e76d0
