### ISSUE TITLE
mdtraj example failing

### ISSUE THREAD

**Issue by bnovak1** [Marcello-Sega/pytim#313]
The mdtraj example is not working (pytim 0.8.1, mdtraj 1.9.2, mdanalysis 0.19.2).

CODE:

import mdtraj
import pytim
from pytim.datafiles import WATER_GRO, WATER_XTC
t = mdtraj.load_xtc(WATER_XTC,top=WATER_GRO)
inter = pytim.ITIM(t)

OUTPUT:

NameError                                 Traceback (most recent call last)
/home/bnovak1/Sync_NAS/CIMM/melting_point/TiNi_Ko_Grabowski_Neugebauer_2015/NiTi/modified_delr_0.4/semigrand/1152_atoms/output/1809.0K/test2.py in <module>()
      4 
      5 t = mdtraj.load_xtc(WATER_XTC,top=WATER_GRO)
----> 6 inter = pytim.ITIM(t)
      7 for step in t[:]:
      8         print('surface atoms: ', repr(inter.atoms.indices))

/home/bnovak1/miniconda3/envs/CIMM2/lib/python2.7/site-packages/pytim/itim.pyc in __init__(self, universe, group, alpha, normal, molecular, max_layers, radii_dict, clu$
ter_cut, cluster_threshold_density, extra_cluster_groups, info, centered, warnings, mesh, autoassign, **kargs)
    193         sanity = SanityCheck(self)
    194         sanity.assign_universe(
--> 195             universe, radii_dict=radii_dict, warnings=warnings)
    196         sanity.assign_alpha(alpha)
    197         sanity.assign_mesh(mesh)

/home/bnovak1/miniconda3/envs/CIMM2/lib/python2.7/site-packages/pytim/sanity_check.pyc in assign_universe(self, input_obj, radii_dict, warnings)
    154     def assign_universe(self, input_obj, radii_dict=None, warnings=False):
    155 
--> 156         self.interface._mode = self._apply_patches(input_obj)
    157         if self.interface._mode is None:
    158             raise Exception(messages.WRONG_UNIVERSE)

/home/bnovak1/miniconda3/envs/CIMM2/lib/python2.7/site-packages/pytim/sanity_check.pyc in _apply_patches(self, input_obj)
    123                 input_obj[0].save_pdb(_file.name)
    124                 self.interface.universe = MDAnalysis.Universe(_file.name)
--> 125                 PatchMDTRAJ(input_obj, self.interface.universe)
    126                 os.remove(_file.name)
    127                 return 'mdtraj'

NameError: global name 'PatchMDTRAJ' is not defined

**Comment by Marcello-Sega** [comment]
Hi, thanks for the heads-up. 
I think #315 should fix this, could you test it on your system using the latest commit from the master branch?

**Comment by bnovak1** [comment]
Yes, that fixed it. Thanks.
