### ISSUE TITLE
ITIM gives different number of surface molecules with mdtraj and default radii_dict for water

### ISSUE THREAD

**Issue by bnovak1** [Marcello-Sega/pytim#320]
With the default radii_dict, ITIM on the water example with mdtraj gives a different number of atoms at the surface compared to ITIM with mdanalysis. When giving the radii explictly, the number of surface atoms is the same when using mdtraj or mdanalysis.

```python
import MDAnalysis as mda
import mdtraj
import pytim
from pytim.datafiles import WATER_GRO, WATER_XTC

# mdanalysis with default radii
u = mda.Universe(WATER_GRO,WATER_XTC)
inter_mdanalysis = pytim.ITIM(u)
for stepu in u.trajectory[:1]:
    print(repr(inter_mdanalysis.atoms))
```
<AtomGroup with 1572 atoms>

```python
# mdtraj with default radii
t = mdtraj.load_xtc(WATER_XTC, top=WATER_GRO, frame=0)
inter_mdtraj = pytim.ITIM(t)
for step in t[0]:
    print(repr(inter_mdtraj.atoms))
```
<AtomGroup with 1761 atoms>

```python
# mdanalysis with radii_dict specified
u = mda.Universe(WATER_GRO,WATER_XTC)
inter_mdanalysis = pytim.ITIM(u, radii_dict={'OW': 1.5828241418604836, 'HW': 0.0})
for stepu in u.trajectory[:1]:
    print(repr(inter_mdanalysis.atoms))
```
<AtomGroup with 1572 atoms>

```python
# mdtraj with radii_dict specified
t = mdtraj.load_xtc(WATER_XTC, top=WATER_GRO, frame=0)
inter_mdtraj = pytim.ITIM(t, radii_dict={'OW': 1.5828241418604836, 'HW': 0.0})
for step in t[0]:
    print(repr(inter_mdtraj.atoms))
```
<AtomGroup with 1572 atoms>

**Comment by Marcello-Sega** [comment]
Thanks again for posting the issue, I think this is related to MDtraj and MDanalysis assigning different atom names when reading a trajectory, e.g.:

    >>> inter_mdtraj.atoms.names
    >>> array(['O', 'H1', 'H2', ..., 'O', 'H1', 'H2'], dtype=object)

    >>> inter_mdanalysis.atoms.names
    >>> array(['OW', 'HW1', 'HW2', ..., 'OW', 'HW1', 'HW2'], dtype=object)

When you use the custom dictionary, 'OW' and 'HW' are chosen as the closest matches for 'O' and 'H1' or 'H2', and this explains why it works.

One option could be to use the 'standard_names=False' option of MDTraj, but it doesn't work on my system, even though the .gro file is passed as a topology... So I guess for the time being it's just better to pass the custom dictionary, but if you have other ideas they're welcome.

**Comment by bnovak1** [comment]
standard_names seems to only be an option for mdtraj.load_pdb, not mdtraj.load_xtc or any of the other trajectory loaders. Maybe radii_dict should be required when using mdtraj. If it is only water that has this problem, the atom names could be just added to the standard dictionary. I will check if mdtraj changes atom names for protein and nucleic acid residues as well.

**Comment by Marcello-Sega** [comment]
Maybe we could patch on the fly mdtraj.load_xtc. I'll have a look into this asap.

**Comment by Marcello-Sega** [comment]
I finally had some time to look at it. Patch #321 partially fixes the issue, as long as pytim is imported *before* loading the trajectory with MDTraj. So, for example:

```python
import MDAnalysis as mda
import mdtraj
import pytim
from pytim.datafiles import WATER_GRO, WATER_XTC

t = mdtraj.load_xtc(WATER_XTC, top=WATER_GRO, frame=0)

list(t.topology.atoms)[0].name
```
    'OW'

But:
```python
import MDAnalysis as mda
import mdtraj
t = mdtraj.load_xtc('./water.xtc', top='./water.gro', frame=0)
import pytim
list(t.topology.atoms)[0].name
```
    'O'

This should not be a big problem in my opinion: @bnovak1 I propose to close the issue if there are no further suggestions / complications.

**Comment by Marcello-Sega** [comment]
So, I close it, for the time being...
