### ISSUE TITLE
Undocumented feature in GITIM

### ISSUE THREAD

**Issue by balazsfabian** [Marcello-Sega/pytim#322]
The parameter buffer_factor is undocumented in GITIM, but it has a significant effect on the interfacial determination. What is the purpose of this variable? How does one choose the optimum value?

This issue was introduced in 80d3c32 : gitim cleanup & fixes (#274)

**Comment by Marcello-Sega** [comment]
The Delaunay tessellation does not handle periodic boundary conditions, therefore one has to physically copy a layer of atoms, of thickness buffer_factor * alpha. Could you produce a convergence test (number of surface atoms vs buffer_factor) that could show the optimal value of buffer_factor in your case?

**Comment by balazsfabian** [comment]
Yeah, sure!
