### ISSUE TITLE
Conda Pytim for OSX

### ISSUE THREAD

**Issue by maalbadri** [Marcello-Sega/pytim#338]
Hi @Marcello-Sega 👋🏼

I just came across this work, looks great! It looks like the conda installation for Mac OS might be restricted to py2.7 from what I can see in list of versions. If this is the case, could you confirm if you plan to update this? 

Cheers!

**Update for Mac OSX users installing via pip:**

You might need to add `CFLAGS='-stdlib=libc++'` prior to `pip install --user --upgrade pytim`

**Comment by Marcello-Sega** [comment]
Hi,

thanks for your message. I planned to update it in fact, but something goes wrong on the CI (only with py3.8) and I didn't figure out (yet) what is happening. In the meantime, you can always download the source from github and installing within  your conda environment using something along the lines of

```
python3 -m pip install --user . 
```` 
(possibly adding the CFLAGS as you mentioned: Thanks for the hint, I will add it to the README)

**Comment by Marcello-Sega** [comment]
Keep this issue open please.

**Comment by thangckt** [comment]
Hi @Marcello-Sega

Can you have a release of Pytim for Windows conda?
Thank

**Comment by Marcello-Sega** [comment]
conda-forge builds now again successfully for osx, v0.9.0 is available on [anaconda](https://anaconda.org/conda-forge/pytim)
