### ISSUE TITLE
Can volume be compute?

### ISSUE THREAD

**Issue by thangckt** [Marcello-Sega/pytim#344]
Hi Marcello,

Is there possible to compute the volume enveloped in GITIM, or volume of space formed by ITIM and periodic bounds of simulation box?

**Comment by Marcello-Sega** [comment]
Hi,

in a slab configuration, you can just compute the separation between the average position of surface atoms on one side and that of the other side. This, times the cross sectional area, would be a good approximation of the volume. For non-planar systems with GITIM, you'd need to make a Monte Carlo sampling. But in that case you don't even need GITIM, just draw random numbers homogeneously distributed in the box, counting how many points have as nearest neighbour (`scipy.spatial.cKDTree` is your friend) an atom of the "internal" phase. This, of course is a more general approach.
