### ISSUE TITLE
problem detecting surface atoms

### ISSUE THREAD

**Issue by Marcello-Sega** [Marcello-Sega/pytim#348]
From #345 @thangckt 

Dear Marcello,

It runs now. Thank you for your update.

I have a problem with pytim.ITIM when I try to detect to the free surface of the simple model as figure (free surface on 'z' and periodicity on 'x' and 'y')
![image](https://user-images.githubusercontent.com/46436648/104444781-98853e80-55db-11eb-8558-6dbfa6fb6175.png)

I use the following code:
##########
import MDAnalysis, pytim
mdaTraj = MDAnalysis.Universe('Model_Al_z001.cfg', format='lammpsdump')
inter = pytim.ITIM(mdaTraj, molecular=False, normal='z')
inter.atoms
#######
and the result return: <AtomGroup with 0 atoms>

Can you give me some hints on what I get wrong?
I attracted the model file here: https://ufile.io/cmi0nxjs

Thank you so much

_Originally posted by @thangckt in https://github.com/Marcello-Sega/pytim/issues/345#issuecomment-759379863_

**Comment by Marcello-Sega** [comment]
Hi @thangckt, 

if you check the positions of the atoms read you find:

```
In [7]: mdaTraj.atoms.positions
Out[7]: 
array([[   0.     ,    0.     ,    0.     ],
       [   0.     ,    0.     , 1624.9851 ],
       [   0.     ,    0.     , 2437.4778 ],
       ...,
       [ 181.5143 ,  181.5143 , 4874.9556 ],
       [ 181.5143 ,  181.5143 , 5687.4478 ],
       [ 181.5143 ,  181.5143 ,  812.49255]], dtype=float32)
```

which is of course not what is supposed to be. 
This is not a pytim issue: you are providing a file which is apparently not in the format expected by MDAnalysis (see the [lammpsdump refererence ](https://userguide.mdanalysis.org/1.0.0/formats/reference/lammpsdump.html) ). As I'm not a lammps expert, I cannot help you further here, sorry.

**Comment by thangckt** [comment]
Dear @Marcello-Sega

Do you mean the values of positions are too large?

**Comment by Marcello-Sega** [comment]
I mean, they're not the one in the file. So, the file is not read correctly.
