### ISSUE TITLE
unreasonable results of intrinsic profiles at distances far from the first layer

### ISSUE THREAD

**Issue by xiaowu759** [Marcello-Sega/pytim#364]
I have successfully (no errors) calculated the intrinsic profile with respective to the first layer for the freestanding film. I find it is reasonable at distances close to the first layer. However, great fluctuations occur at distances far from the first layer. This furthest distance should correspond to the center of the film, so that great fluctuations in the density profile are not expected.  How to cope with it?  The python scipt and resulting data are copied below.

python scipt:
import MDAnalysis as mda
import numpy as np
import pytim
from pytim.observables import Profile
u = mda.Universe('LJ.gro', 'LJ.short.xtc')
g = u.select_atoms('all')
inter = pytim.ITIM(u, alpha=2.5, cluster_cut=4.5)
profile = Profile(interface=inter)

for ts in u.trajectory[:]:
    profile.sample(g)

lower, upper,  avg = profile.get_values(binwidth=0.5)
bins = (lower + upper) / 2.
np.savetxt('profile.dat', list(zip(bins, avg)))
//end of file

resulting data:
-5.035062712938795926e+01 0.000000000000000000e+00
-4.985210606870095518e+01 0.000000000000000000e+00
-4.935358500801394399e+01 0.000000000000000000e+00
-4.885506394732693281e+01 0.000000000000000000e+00
-4.835654288663992872e+01 0.000000000000000000e+00
-4.785802182595291754e+01 0.000000000000000000e+00
-4.735950076526590635e+01 0.000000000000000000e+00
-4.686097970457889517e+01 0.000000000000000000e+00
-4.636245864389188398e+01 0.000000000000000000e+00
-4.586393758320487279e+01 0.000000000000000000e+00
-4.536541652251786871e+01 0.000000000000000000e+00
-4.486689546183085753e+01 0.000000000000000000e+00
-4.436837440114385345e+01 0.000000000000000000e+00
-4.386985334045684226e+01 0.000000000000000000e+00
-4.337133227976983108e+01 0.000000000000000000e+00
-4.287281121908281989e+01 0.000000000000000000e+00
-4.237429015839580870e+01 0.000000000000000000e+00
-4.187576909770879752e+01 1.449272759536325908e-02
-4.137724803702178633e+01 3.225800658322789533e-02
-4.087872697633478225e+01 1.041664795916734214e-02
-4.038020591564777106e+01 1.936795706169340547e-02
-3.988168485496076698e+01 1.859054162362421686e-02
-3.938316379427375580e+01 1.806448368660762069e-02
-3.888464273358674461e+01 2.016033034571494340e-02
-3.838612167289973343e+01 2.176759793827573453e-02
-3.788760061221272224e+01 1.870930490520346032e-02
-3.738907955152571105e+01 1.917743203569530902e-02
-3.689055849083869987e+01 1.952938891259046669e-02
-3.639203743015169579e+01 1.936810541405449212e-02
-3.589351636946469171e+01 1.861534984911493093e-02
-3.539499530877768052e+01 1.937610907085984824e-02
-3.489647424809066933e+01 1.946026327913569567e-02
-3.439795318740365815e+01 1.935515105749004844e-02
-3.389943212671664696e+01 1.892188139810614331e-02
-3.340091106602963578e+01 1.986514233089321790e-02
-3.290239000534262459e+01 1.963342509190037916e-02
-3.240386894465562051e+01 1.939103058098697735e-02
-3.190534788396860932e+01 1.929858295589167300e-02
-3.140682682328159814e+01 1.880571100679631277e-02
-3.090830576259459050e+01 1.942059936917492000e-02
-3.040978470190758287e+01 1.918294684444531509e-02
-2.991126364122057169e+01 1.946983376040790220e-02
-2.941274258053356050e+01 1.919970599363195196e-02
-2.891422151984655287e+01 1.969604878871897627e-02
-2.841570045915954523e+01 1.915730998680769195e-02
-2.791717939847253405e+01 1.937657295848854017e-02
-2.741865833778552286e+01 1.940839313389452342e-02
-2.692013727709851523e+01 1.967623847211384322e-02
-2.642161621641150759e+01 1.914304017663918597e-02
-2.592309515572449641e+01 1.937525276552039960e-02
-2.542457409503748522e+01 1.934865600370361607e-02
-2.492605303435047759e+01 1.921509472467793425e-02
-2.442753197366346996e+01 1.924592952218833267e-02
-2.392901091297645877e+01 1.929158722244531804e-02
-2.343048985228944758e+01 1.902266794084753188e-02
-2.293196879160243640e+01 1.927876866212916915e-02
-2.243344773091542876e+01 1.972800673543309569e-02
-2.193492667022842113e+01 1.930172763408526809e-02
-2.143640560954140994e+01 1.940943129822006105e-02
-2.093788454885439876e+01 1.929648463317657978e-02
-2.043936348816739113e+01 1.955189631696432895e-02
-1.994084242748038349e+01 1.935724353915499463e-02
-1.944232136679337231e+01 1.903861278863661424e-02
-1.894380030610636112e+01 1.915113963524758128e-02
-1.844527924541935349e+01 1.937632504353440505e-02
-1.794675818473234585e+01 1.935590046403035808e-02
-1.744823712404533467e+01 1.939097747162774749e-02
-1.694971606335832348e+01 1.938592350831594077e-02
-1.645119500267131585e+01 1.936542673516332067e-02
-1.595267394198430821e+01 1.906375560572837538e-02
-1.545415288129729703e+01 1.880710621721897596e-02
-1.495563182061028584e+01 1.928766309518091179e-02
-1.445711075992327466e+01 1.951113085439000472e-02
-1.395858969923626702e+01 1.950576627544101452e-02
-1.346006863854925939e+01 1.944158747724345632e-02
-1.296154757786224820e+01 1.897716759763632549e-02
-1.246302651717523702e+01 1.932484503461963030e-02
-1.196450545648822938e+01 1.926312419055146302e-02
-1.146598439580122175e+01 1.931455499936012010e-02
-1.096746333511421057e+01 1.959914325902381224e-02
-1.046894227442719938e+01 1.956927351721393302e-02
-9.970421213740191746e+00 1.964436773014710536e-02
-9.471900153053184113e+00 1.864408577939197578e-02
-8.973379092366172927e+00 1.793961849657403629e-02
-8.474858031679161741e+00 1.870319415697850596e-02
-7.976336970992150555e+00 1.959919453559987035e-02
-7.477815910305142921e+00 2.089975591733926261e-02
-6.979294849618135288e+00 2.065644281206698712e-02
-6.480773788931124102e+00 1.924593753273420860e-02
-5.982252728244112916e+00 1.737777286076639185e-02
-5.483731667557105283e+00 1.624369351447351242e-02
-4.985210606870097649e+00 1.683840784922158856e-02
-4.486689546183086463e+00 1.945033837965195328e-02
-3.988168485496075277e+00 2.363828094721494646e-02
-3.489647424809067644e+00 2.459804801244238476e-02
-2.991126364122060011e+00 1.809994380282325607e-02
-2.492605303435048825e+00 1.161535820148200740e-02
-1.994084242748037639e+00 7.115508993645667038e-03
-1.495563182061030005e+00 4.313275185250832131e-03
-9.970421213740223720e-01 2.272874564688437751e-03
-4.985210606870111860e-01 8.157364297837847982e-04
0.000000000000000000e+00 1.141878033889469762e-01
4.985210606870111860e-01 inf
9.970421213740188193e-01 6.660660099777298399e-05
1.495563182061026453e+00 2.541205390956845626e-05
1.994084242748037639e+00 2.781736763999990617e-05
2.492605303435048825e+00 2.226429894506140258e-05
2.991126364122056458e+00 6.634532499017687583e-05
3.489647424809064091e+00 1.581564409536120657e-04
3.988168485496075277e+00 2.735507339821699729e-04
4.486689546183086463e+00 3.331689266377581759e-04
4.985210606870094097e+00 3.876949202223419627e-04
5.483731667557101730e+00 3.890697563618831438e-04
5.982252728244112916e+00 3.199210863682981219e-04
6.480773788931124102e+00 3.351051919067460122e-04
6.979294849618131735e+00 2.959607143066183632e-04
7.477815910305139369e+00 2.652493143339502610e-04
7.976336970992150555e+00 2.555529669901805646e-04
8.474858031679161741e+00 3.352333372579785367e-04
8.973379092366172927e+00 2.886045755682656051e-04
9.471900153053184113e+00 2.329659928466151059e-04
9.970421213740195299e+00 2.417367392016161684e-04
1.046894227442719938e+01 2.992563080590063870e-04
1.096746333511420346e+01 2.668574355835189168e-04

**Comment by Marcello-Sega** [comment]
Hi,

This is absolutely normal and expected. The maximum distance from the interface that can be sampled correspond to half of the local thickness, but the latter fluctuates, hence the fluctuations in the sampled values (see also the discussion related to the Monte Carlo normalization in https://doi.org/10.1063/1.4776196) 

To make a specific example: suppose that the left surface atoms are at global coordinates -40 and the right surface atoms at +40. A point located at global coordinates 0.5 will contribute to the histogram at an intrinsic distance of -39.5 (from the right surface atoms - we don't want it to contribute to the profile of the left surface, think of it as kind of a minimum image convention). Suppose now a fluctuation of the membrane thickness brings the left and right surface atoms at -39 and +39, respectively. In this case, you will not find any atom at distance -39.5, because the maximum distance is -39. Hence, the large fluctuations in the histogram close to the middle of the slab.

I hope this helps, let me know if it is not yet clear.

**Comment by xiaowu759** [comment]
Thank you very much for the quick reply. It sounds reasonable.
