### ISSUE TITLE
retrieving coordinates of Willard-Chandler interface

### ISSUE THREAD

**Issue by sbkashif** [Marcello-Sega/pytim#390]
I want to use this package to determine the Willard-Chandler interface for a surface that is not flat. I was running the `MICELLE_PDB` example provided in the README. I could run it successfully and visualize the WC interface in the NGL viewer. However, I am unclear on how to retrieve the coordinates of the isodensity surface. I want to utilize the isodensity surface for further analysis. 

```
import MDAnalysis as mda
import pytim
from pytim.datafiles import MICELLE_PDB
import nglview

u = mda.Universe(MICELLE_PDB)
g = u.select_atoms('resname DPC')

interface = pytim.WillardChandler(u, group=g, mesh=1.5, alpha=3.0)
interface.writecube('data.cube')
`interface.writepdb('surface.pdb')`
```
Unlike the ITIM example, I could not retrieve the surface coordinates from `interface.atoms.positions`, or `interface.layers [0]`. The former resulted in the error `*** AttributeError: AtomGroup has no attribute sum.`, while the latter resulted in the error `*** AttributeError: can't set attribute`. I understand that the WC interface might have a different implementation, and these options may not work here. I hence wrote the interface to the pdb file using `interface.writepdb('surface.pdb')`, I could only see DPC and SOL residues and could not find the surface coordinates. 

I don't understand the `cube` file format to be able to infer an isodensity surface at half the bulk density (typical WC definition) from `data.cube` file. Can anyone explain on how can I retrieve the coordinates of the isodensity surface that is being visualized with the following command:

```
# let's add a transparent, red representation for the isodensity surface at 50% density
view.component_1.add_surface(color='red',isolevelType="value",isolevel=0.5,opacity=0.6) 
```

**Comment by Marcello-Sega** [comment]
Hi, and sorry for the late reply.

The Willard Chandler method does *not* identify interfacial atoms, that's why an `interface` of type `WillardChandler` does not have atoms, in fact if you try to access directly the layers you get

```python
In [1]: import MDAnalysis as mda
In [2]: import pytim
In [3]: from pytim.datafiles import MICELLE_PDB
In [4]: u = mda.Universe(MICELLE_PDB)
In [5]: g = u.select_atoms('resname DPC')
In [6]: interface = pytim.WillardChandler(u, group=g, mesh=1.5, alpha=3.0)
In [7]: interface
Out[7]: <pytim.willard_chandler.WillardChandler at 0x7f1ff8380c40>
In [8]: interface._layers
Out[8]: <AtomGroup with 0 atoms>
```

The error you've seen, however, is clearly misleading, I will provide a patch asap, thanks a lot for reporting this!

**Comment by Marcello-Sega** [comment]
Now the behaviour is correct:

```python
In [2]: import MDAnalysis as mda
   ...: import pytim
   ...: from pytim.datafiles import MICELLE_PDB
   ...: 
   ...: u = mda.Universe(MICELLE_PDB)
   ...: g = u.select_atoms('resname DPC')
   ...: inter= pytim.WillardChandler(u, group=g, alpha=3.0, fast=True)
   ...: inter.atoms

Out[2]: <AtomGroup with 0 atoms>
```

The issue was closed automatically because of the pull request, but let me know if there's still something that you think needs fixing.

**Comment by sbkashif** [comment]
Hi Marcello,

Thanks for your response. I agree that the Willard Chandler method does not identify the interfacial atoms. I have one more clarification to make. If I want to know the 'coordinates' of the isosurface, will `interface.triangulated_surface[0]` be the correct reference? This variable stores the vertices of the isosurface identified by the marching cubes algorithm and is also utilized in writing out the `vtk` file. I was trying to visualize the `vtk` file. From the format in which the `vtk` file is currently being written out, VMD throws the following error:

```
vtkplugin) found 'DATASET UNSTRUCTURED_GRID
', expected 'DATASET STRUCTURED_POINTS'
```
Is there something I can do to visualize the `vtk` file in VMD? Currently, the contents include points and normals. 

Alternatively, I wrote the vertices from `interface.triangulated_surface` as carbon atoms in PDB format. Could this be a reasonable approximation of the isosurface? I am just looking for a consistent format that can be utilized for further analysis and simultaneously visualized in VMD.

**Comment by Marcello-Sega** [comment]
Hi,

You can use Paraview to visualize it, or Nglview; However, I think the two are assuming the coordinates to be in row-major and the other in column-major, if I remember correctly. So, you'll have to swap x and z in one of the programs. I don't remember if I added an option in the code to switch between the two, but I might add it if needed.

**Comment by sbkashif** [comment]
Thanks a lot for your input, Dr. Sega. I am using NGLview for now.
