### ISSUE TITLE
warning thrown when masses cannot be guessed

### ISSUE THREAD

**Issue by Marcello-Sega** [Marcello-Sega/pytim#85]
This is ok, but we should add small howto on how to prevent the warnings / supply masses in advance

**Comment by balazsfabian** [comment]
MDA uses the warnings module, more precisely in guessers.py:
```python
 if np.any(masses == 0.0):
     # figure out where the misses were and report
    misses = np.unique(np.asarray(atom_types)[np.where(masses == 0.0)])
    warnings.warn("Failed to guess the mass for the following atom types: {}"
                              "".format(', '.join(misses)))
```
One can add the following snippet in the code, but then it silences _all_ UserWarning-s.
I think they should have named the warning differently, in order to avoid these exact situations...
```python
# ignore warning concerning masses in MDA (an maybe other warnings, too...)
import warnings
warnings.simplefilter("ignore",UserWarning) 
```

**Comment by balazsfabian** [comment]
This issue is solved in commit:
#273 -- Added filter for mass warning in MDA
